name: Automatic Build

on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Project
        run: tsc -p tsconfig.json --outfile userscript.user.js
